# Define basic setup for golangci-lint
linters:
  enable:
    - revive
    - gosec

linters-settings:
  revive:
    enable-all-rules: true
    rules:
      - name: cognitive-complexity
        arguments: [10]
      - name: line-length-limit
        arguments: [120]

issues:
  max-issues-per-linter: 0

run:
  tests: false
  modules-download-mode: readonly
